development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://dgloheaqundllb:32be9d11265491d52f072a5a03901c138fee7488d479be7112f6b70a4cc600cd@ec2-54-163-236-188.compute-1.amazonaws.com:5432/dahsqdrmp8cl62
  channel_prefix: zrostorage_production
